### ISSUE TITLE
V2 Bottom with cutouts for the thin middle layer is missing

### ISSUE THREAD

**Issue by trunneml** [Dreammaker54/3D-printed-case-for-Keebio-Iris-Rev4#1]
I'm printing your case, but I can't find V2 bottom with the cut outs for the thin middle layer. I can see it in this picture https://user-images.githubusercontent.com/55030231/85798108-e8b5b580-b70a-11ea-9d74-6857f8529c8d.png but the stl file is missing.

**Comment by Dreammaker54** [comment]
I believe the thickness of thin version for v1 and v2 are the same. I.e. you can use the button file from v1. I'll double check and update the file later.

**Comment by yz-54** [comment]
> I'm printing your case, but I can't find V2 button with the cut outs for the thin middle layer. I can see it in this picture https://user-images.githubusercontent.com/55030231/85798108-e8b5b580-b70a-11ea-9d74-6857f8529c8d.png but the stl file is missing.

I believe the thickness of thin version for v1 and v2 are the same. I.e. you can use the button file from v1. I'll double check and update the file later.

**Comment by trunneml** [comment]
oh sorry i mean bottom. :(

**Comment by trunneml** [comment]
I fixed the title and the description

**Comment by trunneml** [comment]
I tried to slice  V1 bottom, but the walls are to thin for my printer, and it's smaller as the top layer.

**Comment by yz-54** [comment]
> I tried to slice V1 bottom, but the walls are to thin for my printer, and it's smaller as the top layer.

You are correct, V2 is 1mm larger than V1 sidewise. 
And the bottom files are indeed missing. Let me see if I can still find the file with the correct cutout. If not I'll make some edits in fusion360 then upload them. The original fusion360 file is there too if you know how to make changes yourself.

**Comment by yz-54** [comment]
Missing files are uploaded
